### ISSUE TITLE
Modal position is out of the window.

### ISSUE THREAD

**Issue by maahad767** [sehmaschine/django-filebrowser#395] opened 2021-02-12 07:56 UTC
![image](https://user-images.githubusercontent.com/67506988/107742739-d049e800-6d39-11eb-8558-cc727566710a.png)

Can't see the cross or back link to continue with the uploading unless I zoom out the browser to 65%. Couldn't find any configurable option to change this.

**Comment by sehmaschine** [comment] 2021-02-12 08:23
the filebrowser does not include a modal window to upload. did you customize something? or do you use another package which adds customization to the filebrowser?

**Comment by maahad767** [comment] 2021-02-12 08:32
I am using it for TinyMCE with django-tinymce package.

**Comment by sehmaschine** [comment] 2021-02-12 09:26
not sure, but maybe it's because of django-tinymce. we use the filebrowser with TinyMCE as well, but without django-tinymce. and we do not have a modal window. the upload page is not supposed to open in a modal.

**Comment by maahad767** [comment] 2021-02-12 13:01
Thanks. 
I think you're right. If I find a solution I will post an update here.

**Comment by sehmaschine** [comment] 2021-03-22 14:50
I've checked this and I don't think it's caused by either filebrowser or grappelli. So I'm closing this for now. If you think it's indeed related to one of our packages, please reopen with additional details.

**Closed by sehmaschine** 2021-03-22 14:50 UTC
