### ISSUE TITLE
filebrowser is not working with admin Inline fields

### ISSUE THREAD

**Issue by tarunrazdan** [sehmaschine/django-filebrowser#321] opened 2016-07-07 04:59 UTC
**Pip freeze:**
Django==1.9.7
django-filebrowser==3.7.1
django-grappelli==2.8.1
Pillow==3.3.0
psycopg2==2.6.1

**Model structure:**
1. Product Model
2. Image model:
     product = FK
    img = FileBrowseField("Image", max_length=255, directory="images/",
                          extensions=[".jpg"], blank=True, null=True)

This image model is made tabular inline into product model. Now while adding the image i am getting this **error:**

FB_FileBrowseField.js:13 Uncaught TypeError: Cannot set property 'value' of nullFileSubmit @ FB_FileBrowseField.js:13onclick @ ?pop=1&dir=images/:347

**Comment by sehmaschine** [comment] 2019-11-11 16:57
closing this since I'm not able to reproduce it. filebrowsefield with inlines works fine with my setup. please reopen with additional details, if this still exists.

**Closed by sehmaschine** 2019-11-11 16:57 UTC
