### ISSUE TITLE
Collectstatic gives TypeError: an integer is required (got type str)

### ISSUE THREAD

**Issue by phoebebright** [sehmaschine/django-filebrowser#379] opened 2019-12-26 14:25 UTC
Got this error when running collectstatic and tracked it down to django-filebrowser.  I don't understand the cause but reported a django hack here:

https://stackoverflow.com/questions/55538153/python-manage-py-collectstatic-typeerror-an-integer-is-required-got-type-str

Tried uninstall and reinstalling.  Tried chmod 644 to the directory.  Still getting the issue on both Mac and Ubuntu.  The version installed via pip is 3.12.1

**Comment by sehmaschine** [comment] 2019-12-27 09:19
I don't see why this is an issue with django-filebrowser. If you think it is, please add a more detailed explanation.

**Comment by sehmaschine** [comment] 2020-05-15 08:48
closing this since no further details are given and I'm not able to reproduce it. please reopen with additional details, if you still think this is a bug.

**Closed by sehmaschine** 2020-05-15 08:48 UTC
